name: AmongChat CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        name: Build Android APK AmongChat
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: Cache Gradle packages
              uses: actions/cache@v3
              with:
                path: |
                  ~/.gradle/caches
                  ~/.gradle/wrapper
                key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle.lockfile') }}
                restore-keys: ${{ runner.os }}-gradle-

            - name: Grant execute permission for gradlew
              run: chmod +x ./gradlew

            # Build Debug APK
            - name: Build Debug APK
              run: ./gradlew assembleDebug

            # Upload Debug APK as artifact that can be downloaded
            - name: Upload Debug APK
              uses: actions/upload-artifact@v4
              with:
                name: AmongChat-Debug-APK-${{ github.sha }}
                path: app/build/outputs/apk/debug/app-debug.apk
